### ISSUE TITLE
video and audio is not sync

### ISSUE THREAD

**Issue by xmuben** [peilinok/screen-recorder#22]
Hi, peilinok, thank you for you project.  I test you project and found the video and the speaker is not sync. Just see the attachment.

[amrecorder.log](https://github.com/peilinok/screen-recorder/files/6219064/amrecorder.log)

https://user-images.githubusercontent.com/22139326/112784051-45237800-9083-11eb-8982-97fa88894670.mp4

**Comment by peilinok** [comment]
你用的是最新代码吗？我印象中win7中是有特别的地方

**Comment by harvestsure** [comment]
大佬 我也遇到了音画不同步的问题了（win10系统），现在还在研究您的代码。

**Comment by peilinok** [comment]
> 大佬 我也遇到了音画不同步的问题了（win10系统），现在还在研究您的代码。

不敢当，是用的最新的代码？

**Comment by harvestsure** [comment]
> > 大佬 我也遇到了音画不同步的问题了（win10系统），现在还在研究您的代码。
> 
> 不敢当，是用的最新的代码？

是的，我现在就在研究

**Comment by peilinok** [comment]
> > > 大佬 我也遇到了音画不同步的问题了（win10系统），现在还在研究您的代码。
> > 
> > 
> > 不敢当，是用的最新的代码？
> 
> 是的，我现在就在研究

建议回退到 6b9808a18485a8046a4de2a1962f8e16d3c61de2 试一下

**Comment by harvestsure** [comment]
> > > > 大佬 我也遇到了音画不同步的问题了（win10系统），现在还在研究您的代码。
> > > 
> > > 
> > > 不敢当，是用的最新的代码？
> > 
> > 
> > 是的，我现在就在研究
> 
> 建议回退到 [6b9808a](https://github.com/peilinok/screen-recorder/commit/6b9808a18485a8046a4de2a1962f8e16d3c61de2) 试一下

可以的 这个提交正常运行。另外，最新代码中保存为mkv格式后音视频是同步的。

**Comment by peilinok** [comment]
> 大佬 我也遇到了音画不同步的问题了（win10系统），现在还在研究您的代码。

建议回退版本，上次修改产生了新的问题

**Comment by peilinok** [comment]
> > > > > 大佬 我也遇到了音画不同步的问题了（win10系统），现在还在研究您的代码。
> > > > 
> > > > 
> > > > 不敢当，是用的最新的代码？
> > > 
> > > 
> > > 是的，我现在就在研究
> > 
> > 
> > 建议回退到 [6b9808a](https://github.com/peilinok/screen-recorder/commit/6b9808a18485a8046a4de2a1962f8e16d3c61de2) 试一下
> 
> 可以的 这个提交正常运行。另外，最新代码中保存为mkv格式后音视频是同步的。

非常感谢我会尽快修复，或者你有修复方案亦可直接提PR

**Comment by xmuben** [comment]
目前是用最新的代码，我有时间可以配合你写代码，包括跨平台的

**Comment by peilinok** [comment]
> 目前是用最新的代码，我有时间可以配合你写代码，包括跨平台的

最新的一次提交导致了该问题，我大致猜测为音视频采用新的时间戳后的起始时间有问题了

**Comment by peilinok** [comment]
> 目前是用最新的代码，我有时间可以配合你写代码，包括跨平台的

可以拉一份dev的代码，这个上面有新版的开头

**Comment by peilinok** [comment]
@xmuben @harvestsure 
问题已经修复，write_video中最后将时间戳转换时间基的时候用成了音频流的时间基
